# kubernetes template file that define the objects you want in our deployment

kind: Service
apiVersion: v1
metadata:
  name: one2onetool
spec:
  type: NodePort
  selector:
    app: one2onetool-service
  ports:
  - protocol: TCP
    port: 8080
    nodePort: 8080

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: one2onetool-deployment
  labels:
    app: one2onetool
spec:
  replicas: 2
  selector:
    matchLabels:
      app: one2onetool
  template:
    metadata:
      labels:
        app: one2onetool
    spec:
      containers:
      - name: one2onetool
        image: $DOCKER_IMAGE_NAME:$BUILD_NUMBER
        ports:
        - containerPort: 8080
